### ISSUE TITLE
Execution could not continue.  No player classes defined

### ISSUE THREAD

**Issue by mr2meowsYT** [AFADoomer/Wolf3D#2]
Execution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes definedExecution could not continue.

No player classes defined

**Comment by AFADoomer** [comment]
This was not a useful issue report.  I have no idea what you were doing or how you were running the mod, so have nowhere to start troubleshooting.  

Additionally, this version of the Wolf3D TC is obsolete, and will not be further maintained.  Use the new version of the mod here:  [https://github.com/AFADoomer/Wolf3D-TC-3.0](https://github.com/AFADoomer/Wolf3D-TC-3.0)
