### ISSUE TITLE
Problem in opening in (L,G)ZDoom and Zandronum

### ISSUE THREAD

**Issue by CodyCoding27** [AFADoomer/Wolf3D#9]
ZDoom:
OS: Windows NT (NT 10.0) Build 19045
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
Can't find 'GAMEMAPS.WL3'
Can't find 'GAMEMAPS.SOD'
Can't find 'GAMEMAPS.SD2'
Can't find 'GAMEMAPS.SD3'
W_Init: Init WADfiles.
 adding C:/Users/berna/Downloads/zdoom-2.8.1/zdoom.pk3, 584 lumps
 adding ./doom2.wad, 2919 lumps
 adding C:/Users/berna/Downloads/zdoom-2.8.1/GAMEMAPS.WL6
 adding C:/Users/berna/Downloads/zdoom-2.8.1/Wolf3D.ipk3, 3455 lumps

Execution could not continue.

Script error, "Wolf3D.ipk3:cvarinfo.txt" line 4:
Unknown cvar attribute 'cheat'

Zandronum:
OS: Windows 8 (or higher) (NT 6.2) Build 9200
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
Can't find 'GAMEMAPS.WL3'
Can't find 'GAMEMAPS.SOD'
Can't find 'GAMEMAPS.SD2'
Can't find 'GAMEMAPS.SD3'
W_Init: Init WADfiles.
 adding C:/Users/berna/Downloads/Zandronum/zandronum.pk3, 689 lumps
 adding ./doom2.wad, 2919 lumps
 adding C:/Users/berna/Downloads/zdoom-2.8.1/GAMEMAPS.WL6
 adding C:/Users/berna/Downloads/zdoom-2.8.1/Wolf3D.ipk3, 3455 lumps

Execution could not continue.

Script error, "Wolf3D.ipk3:cvarinfo.txt" line 4:
Unknown cvar attribute 'cheat'

GZDoom:
OS: Windows NT (NT 6.2) Build 9200
    
M_LoadDefaults: Load system defaults.
Can't find 'GAMEMAPS.WL3'
Can't find 'GAMEMAPS.SOD'
Can't find 'GAMEMAPS.SD2'
Can't find 'GAMEMAPS.SD3'
W_Init: Init WADfiles.
 adding C:/Users/berna/Downloads/Minecraft_Doom/gzdoom.pk3, 564 lumps
 adding ./doom2.wad, 2919 lumps
 adding C:/Users/berna/Downloads/zdoom-2.8.1/GAMEMAPS.WL6
 adding C:/Users/berna/Downloads/zdoom-2.8.1/Wolf3D.ipk3, 3455 lumps

Execution could not continue.

Script error, "Wolf3D.ipk3:language.csv" line 1:
Found a string without a language specified.

LZDoom:
LZDoom version 3.88b
OS: Windows 10 (or higher) (NT 10.0) Build 19045
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
Can't find 'GAMEMAPS.WL3'
Can't find 'GAMEMAPS.SOD'
Can't find 'GAMEMAPS.SD2'
Can't find 'GAMEMAPS.SD3'
W_Init: Init WADfiles.
 adding C:/Users/berna/Downloads/LZDoom_3.88b_x64/lzdoom.pk3, 713 lumps
 adding C:/Users/berna/Downloads/LZDoom_3.88b_x64/game_support.pk3, 291 lumps
 adding ./DOOM2.WAD, 2919 lumps
 adding C:/Users/berna/Downloads/LZDoom_3.88b_x64/game_widescreen_gfx.pk3, 211 lumps
 adding C:/Users/berna/Downloads/zdoom-2.8.1/GAMEMAPS.WL6
 adding C:/Users/berna/Downloads/zdoom-2.8.1/Wolf3D.ipk3, 3455 lumps
Cannot load DEFCVARS from a wadfile!
Skipping CSV 'LANGUAGE' lump.
I_Init: Setting up machine state.
CPU speed: 2295 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
  Family 6, Model 42, Stepping 7
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 HyperThreading
Renderer: Software on Direct3D
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device OpenAL Soft on Alto-falantes (2- High Definition Audio Device)
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.

Execution could not continue.

Script error, "Wolf3D.ipk3:animdefs.txt" line 24:
Bad syntax.

Can you fix it, please? (and also make it available for other ports, like ZDoom, Zandronum, etc..?)

**Comment by AFADoomer** [comment]
The target engine for this mod is GZDoom.  You appear to be running a very old version; please upgrade. The [current released version](https://zdoom.org/downloads) is 4.13.

The internal code for this mod is all written in ZScript, which is not supported in Zandronum or ZDoom.  Also, LZDoom is no longer being maintained, so is not compatible, either.

Also, this is the repository for the old version of this mod - Version 3.0's repo is [here](https://github.com/AFADoomer/Wolf3D-TC-3.0).
